package Domain.Enum;

public enum Objetivo {
    MILIONARIO, FAMILIACOMPLETA, CELEBRIDADE, KING, LORDCOMMANDER, EUNUCO, NOONE, THEHAND, FIRSTMAN, FREEMAN, UNSULLIED, LORD, LADY, QUEEN, SOLDIER, KINGSGUARD, PROTECTOR
}
